# Generated by Django 5.1.1 on 2024-09-07 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_customuser_tenantuser_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tenant.client'),
            preserve_default=False,
        ),
    ]
