# Generated by Django 5.1.1 on 2024-09-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tenantuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant',
        ),
    ]
