# Generated by Django 5.0.4 on 2024-04-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_balance', models.IntegerField(blank=True, null=True)),
                ('leave_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_note', models.TextField()),
                ('supervisor_comment', models.TextField()),
                ('leave_request_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('acting_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acting_employee', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.employeeleave')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_supervisor', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual leave', 'Annual Leave'), ('paternity leave', 'Paternity Leave'), ('maternity leave', 'Maternity Leave'), ('sick leave', 'Sick Leave'), ('study leave', 'Study Leave'), ('unpaid leave', 'Unpaid Leave'), ('compensatory time off', 'Compensatory time Off'), ('compassionate leave', 'compassionate Leave')], max_length=150, unique=True)),
                ('number_of_leave_days', models.IntegerField()),
                ('carryover_unused', models.BooleanField()),
                ('employee_leave', models.ManyToManyField(related_name='employee_leaves', through='leave.EmployeeLeave', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleave',
            unique_together={('leave_type', 'employee')},
        ),
    ]
