# Generated by Django 5.0.4 on 2024-04-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='work_day',
            new_name='week_day',
        ),
    ]
