# Generated by Django 4.2.11 on 2024-04-20 03:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tweak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hobbie',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('football', 'Football'), ('reading', 'Reading'), ('Swimming', 'Swimming')], default='football', max_length=125),
        ),
    ]
